config/routes.rb
PortfolioManager::Application.routes.draw do
  resources :portfolios do
    member do
      post 'price_update'
    end
    resources :assets, :constraints => {:id => /.*/}
  end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  # root :to => 'welcome#index'
end

app/models/asset.rb
class Asset

  CLASSES = [:stock, :bond, :cash]

  attr_reader :symbol, :shares, :price, :asset_class

  def initialize(symbol, shares, price, asset_class)
    @symbol = symbol
    @shares = shares.round(3)
    @price = price
    @asset_class = asset_class
  end

  def value
    price * shares
  end

  def ==(other)
    return false unless other.is_a? Asset
    symbol == other.symbol && shares = other.shares && price == other.price && asset_class == other.asset_class
  end

end

app/models/persistence/asset_record.rb
class AssetRecord < ActiveRecord::Base
  attr_accessible :price_in_cents, :shares, :symbol, :asset_class

  validates :price_in_cents, numericality: { greater_than: 0 }

  belongs_to :portfolio, :class_name => "PortfolioRecord"
end

app/models/persistence/portfolio_record.rb
class PortfolioRecord < ActiveRecord::Base
  attr_accessible :name

  has_many :assets, :class_name => "AssetRecord"
end

app/models/persistence/portfolio_repository.rb
class PortfolioRepository

  def self.save(portfolio)
    existing_portfolio = PortfolioRecord.find_by_name(portfolio.name)
    record = existing_portfolio || PortfolioRecord.create!(:name => portfolio.name)
    portfolio.entries.each do |entry|
      asset = record.assets.find_by_symbol(entry.symbol) || record.assets.build
      asset.update_attributes! :symbol => entry.symbol, :shares => entry.shares, :price_in_cents => entry.price.cents, :asset_class => entry.asset_class
    end
    record.id
  end

  def self.load(id)
    record = PortfolioRecord.find(id)
    Portfolio.new(record.name, record.assets.map {|asset| Asset.new(asset.symbol, asset.shares, Money.new(asset.price_in_cents), asset.asset_class.to_sym)})
  end
end

app/models/portfolio.rb
class Portfolio
  include Enumerable

  attr_reader :name, :entries
  def initialize(name, entries = [])
    @name = name
    @entries = entries
  end

  def each
    @entries.each do |entry|
      yield entry
    end
  end

  def value
    @entries.inject(Money.new(0)) { |sum, x| sum + x.value }
  end

  def asset(symbol)
    @entries.select {|n| n.symbol == symbol}.first
  end

  def assets_of_type(asset_class)
    Portfolio.new("#{@name} - #{asset_class}", @entries.select {|n| n.asset_class == asset_class })
  end

  def add(asset)
    Portfolio.new(name, @entries + [asset])
  end

  def update(symbol, shares, price)
    @entry = asset(symbol)
    Portfolio.new(name, @entries - [@entry] + [Asset.new(symbol, shares, price, @entry.asset_class)])
  end

  def update_prices(stock_ticker = StockTicker.new)
    updated_entries = []
    @entries.each do |entry|
      updated_price = stock_ticker.get_price(entry.symbol)
      updated_price = entry.price if updated_price == Money.new(0)
      updated_entries << Asset.new(entry.symbol, entry.shares, updated_price, entry.asset_class)
    end
    Portfolio.new(@name, updated_entries)
  end

  def ==(other)
    return false unless other.is_a? Portfolio
    self.name == other.name && self.entries == other.entries
  end

end

app/models/stock_ticker.rb
require 'stock_quote'

class StockTicker

  def get_price(symbol)
    Money.new(StockQuote::Stock.quote(symbol).last * 100)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/assets_controller.rb
class AssetsController < ApplicationController
  def new
  end

  def create
    portfolio = PortfolioRepository.load(params[:portfolio_id])
    updated_portfolio = portfolio.add(Asset.new(params[:symbol], params[:shares].to_f, Money.parse(params[:price]), params[:asset_class].to_sym))
    saved_id = PortfolioRepository.save(updated_portfolio)
    redirect_to portfolio_url(saved_id)
  end

  def edit
    portfolio = PortfolioRepository.load(params[:portfolio_id])
    @entry = portfolio.asset(params[:id])
  end

  def update
    portfolio = PortfolioRepository.load(params[:portfolio_id])
    @entry = portfolio.asset(params[:id])
    updated_portfolio = portfolio.update(params[:symbol], params[:shares].to_f, Money.parse(params[:price]))
    saved_id = PortfolioRepository.save(updated_portfolio)
    redirect_to portfolio_url(saved_id)
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  def new
  end

  def create
    portfolio = Portfolio.new(params[:name])
    id = PortfolioRepository.save(portfolio)
    redirect_to portfolio_url(id)
  end

  def show
    @portfolio = PortfolioRepository.load(params[:id])
  end

  def price_update
    portfolio = PortfolioRepository.load(params[:id])
    updated_portfolio = portfolio.update_prices
    PortfolioRepository.save(updated_portfolio)
    redirect_to portfolio_url(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def format_decimal(decimal)
    #Removes trailing .0 on floats if it is there
    if decimal == decimal.round
      decimal.round
    else
      decimal
    end
  end

end

app/views/assets/edit.html.erb
<%= form_tag(portfolio_asset_path(params[:portfolio_id]), :method => :put) do %>

  <%= label_tag(:symbol) %>
  <%= text_field_tag(:symbol, @entry.symbol) %><br>

  <%= label_tag(:shares) %>
  <%= text_field_tag(:shares, @entry.shares) %><br>

  <%= label_tag(:price) %>
  <%= text_field_tag(:price, @entry.price.format) %><br>

  <%= label_tag(:asset_class) %>:
  <%= @entry.asset_class.to_s.titleize %><br>

  <%= submit_tag("Save") %>
  <%= link_to "Cancel", portfolio_path(params[:portfolio_id]) %>
<% end %>

app/views/assets/new.html.erb
<%= form_tag(portfolio_assets_path(params[:portfolio_id])) do %>

  <%= label_tag(:symbol) %>
  <%= text_field_tag(:symbol) %><br>

  <%= label_tag(:shares) %>
  <%= text_field_tag(:shares) %><br>

  <%= label_tag(:price) %>
  <%= text_field_tag(:price) %><br>

  <%= label_tag(:asset_class) %>
  <%= select_tag(:asset_class, options_for_select(Asset::CLASSES.map {|n| [n.to_s.titleize, n]})) %><br>

  <%= submit_tag("Add to Portfolio") %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Portfolio Manager</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/portfolios/new.html.erb
<%= form_tag(portfolios_path) do %>
  <%= label_tag(:name) %>
  <%= text_field_tag(:name) %>
  <%= submit_tag("Create Portfolio") %>
<% end %>

app/views/portfolios/show.html.erb
<h1><%= @portfolio.name %></h1>

<% if @portfolio.entries.size > 0 %>
<table>
  <tr>
    <th>Symbol</th>
    <th>Shares</th>
    <th>Price</th>
    <th>Value</th>
    <th>Percentage</th>
    <th></th>
  </tr>
  <% Asset::CLASSES.each do |asset_class| %>
    <tbody class='<%= asset_class.to_s.pluralize %>'>
      <tr><th><%= asset_class.to_s.pluralize.titleize %> (<%= number_to_percentage(@portfolio.assets_of_type(asset_class).value / @portfolio.value * 100, :precision => 1) %>)</th></tr>
      <% @portfolio.assets_of_type(asset_class).each do |entry| %>
        <tr>
          <td><%= entry.symbol %></td>
          <td><%= format_decimal(entry.shares) %></td>
          <td><%= entry.price.format %></td>
          <td><%= entry.value.format %> </td>
          <td><%= number_to_percentage((entry.value / @portfolio.value) * 100, :precision => 1) %></td>
          <td><%= link_to "Edit", edit_portfolio_asset_path(params[:id], entry.symbol) %></td>
        </tr>
      <% end %>
    </tbody>
  <% end %>
</table>
<% end %>
<br>
<%= link_to "Add Asset", new_portfolio_asset_path(params[:id]) %>
<br><br>
<%= button_to "Update Prices", price_update_portfolio_path(params[:id]) %>